#include "WebUI.h"

#include <Arduino.h>

namespace
{
    void SendHttpHeaders(WiFiClient& client, const char* contentType)
    {
        client.println(F("HTTP/1.1 200 OK"));
        client.print(F("Content-Type: "));
        client.println(contentType);
        client.println(F("Connection: close"));
        client.println();
    }
}

namespace WebUI
{
    void SendHomePage(WiFiClient& client)
    {
        SendHttpHeaders(client, "text/html; charset=utf-8");
        client.println(F("<!doctype html><html><head><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"));
        client.println(F("<title>Garden Pump</title><style>body{font-family:system-ui;margin:0;background:#f5f7f4;color:#172018}header{background:#234b36;color:white;padding:16px 20px}main{padding:16px;max-width:960px;margin:auto}.tabs{display:flex;gap:8px;border-bottom:1px solid #d9dfd7;margin-bottom:14px}.tab{border:0;border-bottom:3px solid transparent;background:transparent;border-radius:0;margin:0;padding:10px 12px}.tab.active{border-bottom-color:#2f7d4f;font-weight:700}.panel{display:none}.panel.active{display:block}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.slotgrid{display:grid;grid-template-columns:repeat(2,minmax(220px,1fr));gap:10px;max-width:760px}.card{background:white;border:1px solid #d9dfd7;border-radius:8px;padding:12px}.big{font-size:28px;font-weight:700}.bar{height:10px;background:#dfe6dc;border-radius:999px;overflow:hidden}.fill{height:100%;background:#2f7d4f;width:0}.field{display:block;margin:6px 0}.field input[type=number]{width:72px}.source,.checks,.ranges{display:flex;gap:10px;flex-wrap:wrap;margin:8px 0}.hint{margin:6px 0 12px;color:#4c5a4c}select{max-width:100%}button,a.btn{display:inline-block;margin:4px 4px 4px 0;padding:8px 10px;border:1px solid #9cad9b;border-radius:6px;background:white;color:#172018;text-decoration:none}.range.active{background:#dfeee4;border-color:#2f7d4f}#chart{width:100%;min-height:360px}.uplot{max-width:100%}pre{white-space:pre-wrap;background:#111;color:#eee;padding:12px;border-radius:8px;overflow:auto}@media(max-width:640px){.slotgrid{grid-template-columns:1fr}}</style></head><body>"));
        client.println(F("<header><h1>Garden Pump</h1><div id=\"sub\">Loading...</div></header><main><div class=\"tabs\"><button class=\"tab active\" data-tab=\"dashboard\">Dashboard</button><button class=\"tab\" data-tab=\"stats\">Stats</button></div><section id=\"dashboard\" class=\"panel active\">"));
        client.println(F("<div class=\"grid\"><div class=\"card\"><div>Clock</div><div id=\"clock\">-</div></div><div class=\"card\"><div>WiFi</div><div id=\"wifi\">-</div></div><div class=\"card\"><div>Cloud log</div><div id=\"cloudLog\">-</div></div></div>"));
        client.println(F("<h2>Watering zone override</h2><div class=\"card\"><label><input type=\"radio\" name=\"forcedZone\" value=\"-1\"> off</label><label><input type=\"radio\" name=\"forcedZone\" value=\"0\"> zone 1</label><label><input type=\"radio\" name=\"forcedZone\" value=\"1\"> zone 2</label><label><input type=\"radio\" name=\"forcedZone\" value=\"2\"> zone 3</label><label><input type=\"radio\" name=\"forcedZone\" value=\"3\"> zone 4</label><label class=\"field\">Switch interval (seconds) <input id=\"zoneSwitchInterval\" type=\"number\" min=\"10\" max=\"86400\"></label><button id=\"saveZoneSwitchInterval\">Save interval</button></div>"));
        client.println(F("<h2>Irrigation zones</h2><div class=\"slotgrid\" id=\"irrigationZones\"></div>"));
        client.println(F("<h2>Simulation</h2><div class=\"card\" id=\"simulationControls\"><label><input id=\"simulationEnabled\" type=\"checkbox\"> simulate sensor moisture</label><div class=\"slotgrid\" id=\"simulationCells\"></div><button id=\"saveSimulation\">Apply simulation</button></div>"));
        client.println(F("<h2>Sensors</h2><div class=\"hint\">Use Analog diag for raw A0..A3 reads.</div><div class=\"slotgrid\" id=\"sensors\"></div><h2>Controls</h2>"));
        client.println(F("<a class=\"btn\" href=\"/api/diag\">DIAG</a><a class=\"btn\" href=\"/api/analog_diag\">Analog diag</a><a class=\"btn\" href=\"/api/pipeline_log\">Pipeline log</a><a class=\"btn\" href=\"/api/sync_time\">Sync time</a><a class=\"btn\" href=\"/api/test_cloud_log\">Test cloud log</a>"));
        client.println(F("<h2>Output</h2><pre id=\"out\"></pre><h2>Pipeline</h2><button class=\"btn\" id=\"refreshPipeline\">Refresh pipeline</button><pre id=\"pipeline\">Loading...</pre></section>"));
        client.println(F("<section id=\"stats\" class=\"panel\"><h2>Stats</h2><div class=\"card\"><div class=\"ranges\"><button class=\"range active\" data-range=\"24h\">24h</button><button class=\"range\" data-range=\"7d\">7d</button><button class=\"range\" data-range=\"30d\">30d</button><button class=\"range\" data-range=\"1y\">1y</button><button class=\"range\" data-range=\"all\">All</button></div><div class=\"checks\" id=\"seriesChecks\"></div><div id=\"chart\"></div><div class=\"hint\" id=\"chartStatus\">Open the Stats tab to load chart data.</div></div></section><script>"));
        client.println(F("let forcedBusyUntil=0,sensorBusyUntil=0,zoneBusyUntil=0,simulationBusyUntil=0,statusBusy=false,apiBusy=false,pipelineBusy=false,statsBusy=false"));
        client.println(F("let chartLoaded=false,chart=null,chartRows=[],chartRange='24h';"));
        client.println(F("const seriesDefs=[{id:'s1',label:'Sensor 1',key:'Sensor 1',scale:'pct',stroke:'#2f7d4f',show:true},{id:'s2',label:'Sensor 2',key:'Sensor 2',scale:'pct',stroke:'#1565c0',show:true},{id:'s3',label:'Sensor 3',key:'Sensor 3',scale:'pct',stroke:'#8e44ad',show:false},{id:'s4',label:'Sensor 4',key:'Sensor 4',scale:'pct',stroke:'#b26a00',show:false},{id:'w1',label:'Zone 1 water',key:'Irrigation Zone 1 (mL)',scale:'ml',stroke:'#3b7a57',show:true},{id:'w2',label:'Zone 2 water',key:'Irrigation Zone 2 (mL)',scale:'ml',stroke:'#1f77b4',show:true},{id:'w3',label:'Zone 3 water',key:'Irrigation Zone 3 (mL)',scale:'ml',stroke:'#9467bd',show:true},{id:'w4',label:'Zone 4 water',key:'Irrigation Zone 4 (mL)',scale:'ml',stroke:'#ff7f0e',show:true},{id:'r1',label:'Zone 1 relay',key:'relay1',scale:'relay',stroke:'#234b36',show:false},{id:'r2',label:'Zone 2 relay',key:'relay2',scale:'relay',stroke:'#0d47a1',show:false},{id:'r3',label:'Zone 3 relay',key:'relay3',scale:'relay',stroke:'#6a1b9a',show:false},{id:'r4',label:'Zone 4 relay',key:'relay4',scale:'relay',stroke:'#bf360c',show:false}];"));
        client.println(F("function esc(v){return encodeURIComponent(v)}"));
        client.println(F("function tabTo(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id));if(id==='stats')loadStats()}"));
        client.println(F("function relayBit(row,i){let m=Number(row['Relay Bitmask']||0);return (m&(1<<(i-1)))?1:0}function rowTime(row){return Math.floor(new Date(row.TimeStamp).getTime()/1000)}function rangeLimit(){return chartRange==='24h'?144:chartRange==='7d'?1008:chartRange==='30d'?4320:chartRange==='1y'?52560:5000}"));
        client.println(F("function buildSeriesChecks(){seriesChecks.innerHTML=seriesDefs.map(d=>'<label><input type=\"checkbox\" data-series=\"'+d.id+'\" '+(d.show?'checked':'')+'> '+d.label+'</label>').join('');seriesChecks.onchange=e=>{let d=seriesDefs.find(x=>x.id===e.target.dataset.series);if(d){d.show=e.target.checked;renderChart()}}}"));
        client.println(F("function loadPlotLib(){return new Promise((res,rej)=>{if(window.uPlot)return res();let l=document.createElement('link');l.rel='stylesheet';l.href='https://cdn.jsdelivr.net/npm/uplot@1.6.30/dist/uPlot.min.css';document.head.appendChild(l);let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/uplot@1.6.30/dist/uPlot.iife.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}"));
        client.println(F("async function fetchStats(){chartStatus.textContent='Loading chart data...';let r=await fetch('/api/history?limit='+rangeLimit());chartRows=await r.json();chartStatus.textContent=chartRows.length+' rows loaded'}"));
        client.println(F("function renderChart(){if(!window.uPlot||!chartRows.length)return;let el=document.getElementById('chart');let defs=seriesDefs.filter(d=>d.show);let x=chartRows.map(rowTime);let data=[x];defs.forEach(d=>data.push(chartRows.map(r=>d.id[0]==='r'?relayBit(r,Number(d.id[1])):Number(r[d.key]||0))));let opts={width:Math.max(320,el.clientWidth||900),height:360,scales:{x:{time:true},pct:{range:[0,100]},ml:{auto:true},relay:{range:[0,1]}},axes:[{}, {scale:'pct',label:'moisture %'}, {scale:'ml',side:1,label:'water ml'}, {scale:'relay',side:1,label:'relay'}],series:[{},...defs.map(d=>({label:d.label,scale:d.scale,stroke:d.stroke,width:2,points:{show:false},paths:d.scale==='relay'?uPlot.paths.stepped({align:1}):null}))]};if(chart)chart.destroy();chart=new uPlot(opts,data,el)}"));
        client.println(F("async function waitForDashboardPolls(){while(statusBusy||pipelineBusy||apiBusy)await new Promise(r=>setTimeout(r,25))}async function loadStats(){if(chartLoaded)return;chartLoaded=true;statsBusy=true;buildSeriesChecks();try{await waitForDashboardPolls();await loadPlotLib();await fetchStats();renderChart()}catch(e){chartStatus.textContent='Chart load failed: '+e}finally{statsBusy=false}}"));
        client.println(F("async function api(p){if(apiBusy)return;apiBusy=true;out.textContent='Working...';try{let r=await fetch(p);out.textContent=await r.text()}catch(e){out.textContent='Request failed: '+e}finally{apiBusy=false;status()}}"));
        client.println(F("function card(c){let pct=Math.max(0,Math.min(100,c.moisturePercent||0));let h='<div class=\"card\"><b>Slot '+(c.index+1)+'</b><div>source '+c.sensorSource+' / '+c.analogPin+' ('+c.analogPinNumber+')</div><div>internal cell '+c.index+' addr '+c.address+'</div><div>'+(c.connected?'connected':'not connected')+' / '+(c.error?'error':'ok')+'</div>';"));
        client.println(F("if(c.sensorSource==='vh400'){h+='<div>voltage '+c.voltageMv+' mV / VWC '+c.vwcPercent.toFixed(1)+'%</div><div>confidence '+c.vh400ConnectionScore+' / spread '+c.readSpread+' / accepted '+c.acceptedReads+'</div>'}else if(c.sensorSource==='seesaw'){h+='<div>raw '+c.raw+' / filtered '+c.filteredRaw+'</div><div>spread '+c.readSpread+' / accepted '+c.acceptedReads+'</div>'}else{h+='<div>not installed</div>'}"));
        client.println(F("h+='<div>relay '+(c.relay?'open':'closed')+'</div><div class=\"bar\"><div class=\"fill\" style=\"width:'+pct+'%\"></div></div><div>moisture '+pct.toFixed(1)+'%</div>';"));
        client.println(F("h+='<div class=\"source\"><label><input type=\"radio\" name=\"source'+c.index+'\" value=\"unused\" '+(c.sensorSource==='unused'?'checked':'')+'> not used</label><label><input type=\"radio\" name=\"source'+c.index+'\" value=\"seesaw\" '+(c.sensorSource==='seesaw'?'checked':'')+'> seesaw</label><label><input type=\"radio\" name=\"source'+c.index+'\" value=\"vh400\" '+(c.sensorSource==='vh400'?'checked':'')+'> VH400</label></div>';"));
        client.println(F("h+='<label class=\"field\">Start below <input id=\"st'+c.index+'\" type=\"number\" min=\"0\" max=\"100\" value=\"'+c.startThreshold+'\"> %</label><label class=\"field\">Stop above <input id=\"sp'+c.index+'\" type=\"number\" min=\"0\" max=\"100\" value=\"'+c.stopThreshold+'\"> %</label><button onclick=\"setThreshold('+c.index+')\">Save watering</button>';"));
        client.println(F("if(c.sensorSource==='seesaw'){h+='<div>calibration raw '+c.dryCalibrationRaw+'..'+c.wetCalibrationRaw+'</div><label>dry <input id=\"dry'+c.index+'\" type=\"number\" min=\"0\" max=\"1022\" placeholder=\"'+c.dryCalibrationRaw+'\"></label><label> wet <input id=\"wet'+c.index+'\" type=\"number\" min=\"1\" max=\"1023\" placeholder=\"'+c.wetCalibrationRaw+'\"></label><button onclick=\"setCalibration('+c.index+')\">Save cal</button><button onclick=\"useCurrentDry('+c.index+','+c.filteredRaw+')\">Use dry</button><button onclick=\"useCurrentWet('+c.index+','+c.filteredRaw+')\">Use wet</button>'}h+='</div>';return h}"));
        client.println(F("function simCard(c){return '<div><label>slot '+(c.index+1)+' <input id=\"sim'+c.index+'\" type=\"range\" min=\"0\" max=\"100\" value=\"'+c.simulatedMoisturePercent+'\"></label><input id=\"simn'+c.index+'\" type=\"number\" min=\"0\" max=\"100\" value=\"'+c.simulatedMoisturePercent+'\"></div>'}"));
        client.println(F("function fmtWater(ml){return ml>=1000?(ml/1000).toFixed(2)+' L':ml.toFixed(0)+' ml'}function fmtTime(sec){return sec>=3600?(sec/3600).toFixed(1)+' h':sec>=60?(sec/60).toFixed(1)+' min':sec+' s'}"));
        client.println(F("function zoneCard(z){let h='<div class=\"card\"><b>Zone '+(z.index+1)+'</b><div><b>Relay status '+(z.relay?'open':'closed')+'</b></div><div>'+(z.needsWater?'needs water':'not requesting water')+'</div><div>water runtime '+fmtTime(z.waterOpenSeconds||0)+'</div><div>water estimate '+fmtWater(z.estimatedWaterMl||0)+' @ '+(window.flowMlps||0).toFixed(1)+' ml/s</div>';h+='<label class=\"field\">Sensor <select name=\"zoneSensor'+z.index+'\">';for(let i=0;i<4;i++)h+='<option value=\"'+i+'\" '+(z.sensor===i?'selected':'')+'>slot '+(i+1)+'</option>';h+='</select></label></div>';return h}"));
        client.println(F("function visualCells(cells){let order=[0,2,1,3];return cells.slice().sort((a,b)=>order.indexOf(a.index)-order.indexOf(b.index))}"));
        client.println(F("async function pipelineLog(){if(pipelineBusy||apiBusy||statsBusy||!dashboard.classList.contains('active'))return;pipelineBusy=true;try{let r=await fetch('/api/pipeline_latest');let t=await r.text();pipeline.textContent=(t+'\\n'+pipeline.textContent).slice(0,16000)}catch(e){pipeline.textContent='Pipeline request failed: '+e+'\\n'+pipeline.textContent}finally{pipelineBusy=false}}async function pipelineHistory(){if(pipelineBusy||apiBusy)return;pipelineBusy=true;try{let r=await fetch('/api/pipeline_log');pipeline.textContent=await r.text()}catch(e){pipeline.textContent='Pipeline history failed: '+e}finally{pipelineBusy=false}}"));
        client.println(F("async function status(){if(statusBusy||apiBusy||statsBusy||!dashboard.classList.contains('active'))return;statusBusy=true;try{let r=await fetch('/api/status');let s=await r.json();window.flowMlps=s.estimatedFlowMlPerSecond||0;let vc=visualCells(s.cells);clock.textContent=s.time+(s.timeSynced?'':' (not synced)');wifi.textContent=(s.wifiConfigured?s.wifiSsid:'not configured')+' '+s.ip+' '+s.rssi+' dBm';cloudLog.textContent=(s.cloudLogConfigured?'configured':'not configured')+' / '+(s.cloudLogOk?'ok':'not ok')+' / '+(s.cloudLogMessage||'-');if(!zoneSwitchInterval.value)zoneSwitchInterval.value=s.zoneSwitchIntervalSeconds;"));
        client.println(F("if(Date.now()>forcedBusyUntil)document.querySelectorAll('input[name=forcedZone]').forEach(x=>x.checked=Number(x.value)===s.activeIrrigationZone);if(Date.now()>zoneBusyUntil&&!irrigationZones.matches(':focus-within'))irrigationZones.innerHTML=visualCells(s.zones).map(zoneCard).join('');if(Date.now()>simulationBusyUntil&&!simulationControls.matches(':focus-within')){simulationEnabled.checked=s.simulationEnabled;simulationCells.innerHTML=vc.map(simCard).join('');document.querySelectorAll('#simulationCells input[type=range]').forEach(x=>x.oninput=()=>{document.getElementById('simn'+x.id.substring(3)).value=x.value});document.querySelectorAll('#simulationCells input[type=number]').forEach(x=>x.oninput=()=>{document.getElementById('sim'+x.id.substring(4)).value=x.value})}let state=!s.operationsStarted?'waiting for clock':(s.outOfMemory?'log full':'logging available');if(s.simulationEnabled)state+=' (simulation)';if(s.activeIrrigationZone>=0)state+=' (zone '+(s.activeIrrigationZone+1)+' open)';if(s.startupTimeWaitTimedOut)state+=' (time sync timed out)';sub.textContent='http://'+s.ip+' - '+state;if(Date.now()>sensorBusyUntil&&!sensors.matches(':focus-within'))sensors.innerHTML=vc.map(card).join('')}finally{statusBusy=false}}"));
        client.println(F("async function setThreshold(i){sensorBusyUntil=Date.now()+3000;api('/api/set_threshold?cell='+i+'&start='+esc(document.getElementById('st'+i).value)+'&stop='+esc(document.getElementById('sp'+i).value))}"));
        client.println(F("function inputValueOrPlaceholder(id){let e=document.getElementById(id);return e.value||e.placeholder}async function setCalibration(i){sensorBusyUntil=Date.now()+3000;api('/api/set_calibration?cell='+i+'&dry='+esc(inputValueOrPlaceholder('dry'+i))+'&wet='+esc(inputValueOrPlaceholder('wet'+i)))}"));
        client.println(F("function useCurrentDry(i,v){document.getElementById('dry'+i).value=v;setCalibration(i)}function useCurrentWet(i,v){document.getElementById('wet'+i).value=v;setCalibration(i)}"));
        client.println(F("async function setSensorSource(i,v){sensorBusyUntil=Date.now()+3000;api('/api/set_sensor_source?cell='+i+'&source='+esc(v))}"));
        client.println(F("async function setZoneSensor(i,v){zoneBusyUntil=Date.now()+3000;api('/api/set_zone_sensor?zone='+i+'&sensor='+esc(v))}"));
        client.println(F("async function applySimulation(){simulationBusyUntil=Date.now()+3000;let p='/api/set_simulation?enabled='+(simulationEnabled.checked?1:0);for(let i=0;i<4;i++)p+='&c'+i+'='+esc(document.getElementById('simn'+i).value);api(p)}"));
        client.println(F("document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>tabTo(b.dataset.tab));document.querySelectorAll('.range').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.range').forEach(x=>x.classList.remove('active'));b.classList.add('active');chartRange=b.dataset.range;chartLoaded=false;await loadStats()});document.querySelectorAll('a.btn').forEach(a=>a.onclick=e=>{e.preventDefault();api(a.getAttribute('href'))});document.querySelectorAll('input[name=forcedZone]').forEach(x=>x.onchange=()=>{forcedBusyUntil=Date.now()+3000;api('/api/set_forced_irrigation?zone='+esc(x.value))});sensors.onchange=e=>{let n=e.target.name||'';if(n.startsWith('source'))setSensorSource(Number(n.substring(6)),e.target.value)};irrigationZones.onchange=e=>{let n=e.target.name||'';if(n.startsWith('zoneSensor'))setZoneSensor(Number(n.substring(10)),e.target.value)};saveSimulation.onclick=applySimulation;saveZoneSwitchInterval.onclick=()=>api('/api/set_zone_switch_interval?seconds='+esc(zoneSwitchInterval.value));refreshPipeline.onclick=pipelineHistory;status();pipelineLog();setInterval(status,5000)"));
        client.println(F("</script></main></body></html>"));
    }
}
